import { motion } from 'framer-motion'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { MaterialIcon } from '../../components/MaterialIcon'
import { AI_SUGGESTIONS_PATH, DATA_UPLOAD_PATH } from '../../config/nav'
import { useAnalysisFlow } from '../../context/AnalysisFlowContext'
import { WorkspacePage } from '../../layouts/WorkspacePage'
import type { DatasetColumn } from '../../types/api'
import styles from './DataSettingsScreen.module.css'

const easeOut = [0.22, 1, 0.36, 1] as const

function defaultDisplayName(name: string): string {
  if (!name.includes('_')) {
    return name
  }
  return name
    .split('_')
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase())
    .join('_')
}

function defaultDisplayLabel(col: DatasetColumn): string {
  return col.display_name?.trim() || col.suggested_short_label?.trim() || defaultDisplayName(col.name)
}

function previewColumnHeaderLabel(col: DatasetColumn, renameByCol: Record<string, string>): string {
  const edited = renameByCol[col.name]?.trim()
  return (edited || defaultDisplayLabel(col)).toUpperCase()
}

function isAutoGeneratedColumnName(name: string): boolean {
  const n = name.trim()
  if (!n) {
    return true
  }
  if (/^unnamed(?::|\s|$)/i.test(n)) {
    return true
  }
  if (/^column\s*\d+$/i.test(n)) {
    return true
  }
  return false
}

function friendlyPlaceholderColumnTitle(technicalName: string): string {
  const m = /^unnamed\s*:\s*(\d+)$/i.exec(technicalName.trim())
  if (m) {
    return `Columna ${parseInt(m[1], 10) + 1}`
  }
  return 'Campo sin encabezado'
}

/**
 * In mapping, avoid showing raw “Unnamed: N” when pandas/Excel had no header: show IA label or a short fallback.
 */
function mappingOriginalDisplayed(col: DatasetColumn): string {
  const label = defaultDisplayLabel(col).trim()
  if (label && !isAutoGeneratedColumnName(label)) {
    return label
  }
  if (!isAutoGeneratedColumnName(col.name)) {
    return col.name
  }
  return friendlyPlaceholderColumnTitle(col.name)
}

function isStatusColumn(name: string): boolean {
  return /estado|status|^state$/i.test(name)
}

function showHeaderTypeSelect(col: DatasetColumn, index: number): boolean {
  if (index === 0) {
    return false
  }
  if (isStatusColumn(col.name)) {
    return false
  }
  return true
}

function mappingRowIcon(kind: DatasetColumn['kind']): string {
  if (kind === 'datetime') {
    return 'calendar_today'
  }
  if (kind === 'numeric') {
    return 'numbers'
  }
  return 'short_text'
}

function suggestedRoleLabel(col: DatasetColumn): string {
  if (col.kind === 'datetime') {
    return 'Eje temporal'
  }
  if (col.kind === 'numeric') {
    return 'Métrica continua'
  }
  if (/(^id$|_id$|^uuid|order|referencia)/i.test(col.name)) {
    return 'ID transaccional'
  }
  return 'Dimensión / texto'
}

function StatusBadge({ value }: { value: string }) {
  const u = value.toUpperCase()
  let variant = styles.badgeNeutral
  if (
    u.includes('COMPLET') ||
    u.includes('DONE') ||
    u.includes('OK') ||
    u.includes('SUCCESS')
  ) {
    variant = styles.badgeOk
  } else if (u.includes('PEND') || u.includes('WAIT') || u.includes('PROG')) {
    variant = styles.badgeWarn
  } else if (u.includes('FALL') || u.includes('FAIL') || u.includes('ERROR') || u.includes('CANC')) {
    variant = styles.badgeErr
  }
  const label = value.length > 11 ? `${value.slice(0, 5)}…` : value
  return <span className={variant}>{label.toUpperCase()}</span>
}

/**
 * DataFrame configuration: Stitch-style layout with live dataset from the last analyze response.
 */
export function DataSettingsScreen() {
  const navigate = useNavigate()
  const { datasetProfile, activeFileLabel, uploadId } = useAnalysisFlow()
  const [typeByCol, setTypeByCol] = useState<Record<string, string>>({})
  const [renameByCol, setRenameByCol] = useState<Record<string, string>>({})
  const [search, setSearch] = useState('')

  const applyBaseline = useCallback(() => {
    if (!datasetProfile) {
      return
    }
    const types: Record<string, string> = {}
    const renames: Record<string, string> = {}
    for (const c of datasetProfile.columns) {
      types[c.name] = c.default_select
      renames[c.name] = defaultDisplayLabel(c)
    }
    setTypeByCol(types)
    setRenameByCol(renames)
    setSearch('')
  }, [datasetProfile])

  useEffect(() => {
    applyBaseline()
  }, [applyBaseline, uploadId])

  const filteredColumns = useMemo(() => {
    if (!datasetProfile) {
      return []
    }
    const q = search.trim().toLowerCase()
    if (!q) {
      return datasetProfile.columns
    }
    return datasetProfile.columns.filter((c) => {
      const display = mappingOriginalDisplayed(c).toLowerCase()
      return c.name.toLowerCase().includes(q) || display.includes(q)
    })
  }, [datasetProfile, search])

  const typeTotal = useMemo(() => {
    if (!datasetProfile) {
      return 0
    }
    const { strings, numerics, datetimes } = datasetProfile.type_distribution
    return Math.max(1, strings + numerics + datetimes)
  }, [datasetProfile])

  const integrityHint =
    datasetProfile && datasetProfile.integrity_percent >= 95 ? '+0.2% vs previo' : null

  if (!datasetProfile || !uploadId) {
    return (
      <WorkspacePage
        layoutWide
        title="Datos procesados"
        description="Previsualice y ajuste los tipos de datos antes del procesamiento final."
      >
        <motion.div
          className={styles.emptyState}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45, ease: easeOut }}
        >
          <MaterialIcon name="table_chart" className={styles.emptyIcon} />
          <p className={styles.emptyTitle}>No hay datos cargados</p>
          <p className={styles.emptyLead}>
            Suba un archivo CSV o Excel para generar la vista previa, el mapeo de columnas y el
            resumen estadístico.
          </p>
          <Link className={styles.emptyCta} to={DATA_UPLOAD_PATH}>
            Ir a cargar datos
          </Link>
        </motion.div>
      </WorkspacePage>
    )
  }

  const { row_count, column_count, sample_tag, null_cells, duplicate_rows } = datasetProfile

  return (
    <WorkspacePage
      layoutWide
      title="Datos procesados"
      description="Previsualice y ajuste los tipos de datos antes del procesamiento final."
      toolbar={
        <>
          <button type="button" className={styles.toolbarSecondary} onClick={applyBaseline}>
            <MaterialIcon name="refresh" />
            Revertir Cambios
          </button>
          <button
            type="button"
            className={styles.toolbarPrimary}
            disabled={!uploadId || !datasetProfile}
            title={
              !uploadId || !datasetProfile
                ? 'Se requiere una sesión de datos activa'
                : undefined
            }
            onClick={() => {
              if (!uploadId || !datasetProfile) {
                return
              }
              navigate(AI_SUGGESTIONS_PATH)
            }}
          >
            <MaterialIcon name="save" />
            Confirmar Estructura
          </button>
        </>
      }
    >
      <div className={styles.bento}>
        <div className={styles.mainCol}>
          <motion.section
            className={styles.previewCard}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.42, ease: easeOut }}
          >
            <header className={styles.previewTop}>
              <h2 className={styles.cardTitle}>Vista Previa de Datos</h2>
              <div className={styles.previewMeta}>
                <span>{column_count} COLUMNAS</span>
                <span>{row_count.toLocaleString('es-ES')} FILAS</span>
                <span className={styles.samplePill}>{sample_tag}</span>
              </div>
            </header>
            <label className={styles.searchRow}>
              <MaterialIcon name="search" className={styles.searchIcon} />
              <input
                type="search"
                className={styles.searchInput}
                placeholder="Buscar columnas…"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                aria-label="Buscar columnas"
              />
            </label>
            <div className={styles.tableScroll}>
              {filteredColumns.length === 0 ? (
                <p className={styles.noMatch}>Ninguna columna coincide con la búsqueda.</p>
              ) : (
                <table className={styles.dataTable}>
                  <thead>
                    <tr>
                      {filteredColumns.map((col, idx) => (
                        <th key={col.name} className={styles.th}>
                          {showHeaderTypeSelect(col, idx) ? (
                            <div className={styles.thStack}>
                              <span className={styles.thName}>
                                {previewColumnHeaderLabel(col, renameByCol)}
                              </span>
                              <select
                                className={styles.thSelect}
                                value={typeByCol[col.name] ?? col.default_select}
                                onChange={(e) =>
                                  setTypeByCol((m) => ({ ...m, [col.name]: e.target.value }))
                                }
                                aria-label={`Tipo para ${col.name}`}
                              >
                                {col.select_options.map((opt) => (
                                  <option key={opt} value={opt}>
                                    {opt}
                                  </option>
                                ))}
                              </select>
                            </div>
                          ) : (
                            <span className={styles.thPlain}>{previewColumnHeaderLabel(col, renameByCol)}</span>
                          )}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {datasetProfile.preview_rows.map((row, rIdx) => (
                      <tr key={`r-${rIdx}`} className={styles.tr}>
                        {filteredColumns.map((col, cIdx) => {
                          const raw = row[col.name] ?? ''
                          if (isStatusColumn(col.name)) {
                            return (
                              <td key={col.name} className={styles.td}>
                                {raw ? <StatusBadge value={raw} /> : ''}
                              </td>
                            )
                          }
                          if (col.kind === 'numeric') {
                            return (
                              <td key={col.name} className={`${styles.td} ${styles.tdNumeric}`}>
                                {raw}
                              </td>
                            )
                          }
                          if (cIdx === 0) {
                            return (
                              <td key={col.name} className={`${styles.td} ${styles.tdMuted}`}>
                                {raw}
                              </td>
                            )
                          }
                          return (
                            <td key={col.name} className={styles.td}>
                              {raw}
                            </td>
                          )
                        })}
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          </motion.section>

          <motion.section
            className={styles.mappingCard}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.42, delay: 0.06, ease: easeOut }}
          >
            <h3 className={styles.cardTitle}>Mapeo de Columnas</h3>
            <div className={styles.mappingList}>
              {filteredColumns.map((col) => (
                <motion.div
                  key={col.name}
                  layout
                  className={styles.mappingRow}
                  transition={{ type: 'spring', stiffness: 380, damping: 28 }}
                >
                  <div className={styles.mappingIcon}>
                    <MaterialIcon name={mappingRowIcon(col.kind)} />
                  </div>
                  <div className={styles.mappingGrid}>
                    <div>
                      <span className={styles.mappingLabel}>ORIGINAL</span>
                      <p className={styles.mappingOriginal}>{mappingOriginalDisplayed(col)}</p>
                      <span className={styles.mappingRole}>{suggestedRoleLabel(col)}</span>
                    </div>
                    <div>
                      <span className={`${styles.mappingLabel} ${styles.mappingLabelAccent}`}>
                        NUEVO NOMBRE
                      </span>
                      <input
                        type="text"
                        className={styles.mappingInput}
                        value={renameByCol[col.name] ?? ''}
                        onChange={(e) =>
                          setRenameByCol((m) => ({ ...m, [col.name]: e.target.value }))
                        }
                        aria-label={`Nuevo nombre para ${col.name}`}
                      />
                    </div>
                  </div>
                  <button
                    type="button"
                    className={styles.mappingRevert}
                    title="Restaurar nombre original"
                    aria-label={`Restaurar nombre original de ${col.name}`}
                    onClick={() =>
                      setRenameByCol((m) => ({ ...m, [col.name]: defaultDisplayLabel(col) }))
                    }
                  >
                    <MaterialIcon name="refresh" />
                  </button>
                </motion.div>
              ))}
            </div>
          </motion.section>
        </div>

        <aside className={styles.sideCol}>
          <motion.div
            className={styles.statsCard}
            initial={{ opacity: 0, x: 12 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.42, ease: easeOut }}
          >
            <div className={styles.statsHead}>
              <h3 className={styles.cardTitle}>Resumen Estadístico</h3>
              <MaterialIcon name="analytics" className={styles.statsGlyph} />
            </div>
            <div className={styles.integrityBlock}>
              <p className={styles.statKicker}>INTEGRIDAD DE DATOS</p>
              <div className={styles.integrityRow}>
                <span className={styles.integrityPct}>
                  {datasetProfile.integrity_percent.toLocaleString('es-ES', {
                    minimumFractionDigits: 1,
                    maximumFractionDigits: 1,
                  })}
                  %
                </span>
                {integrityHint ? (
                  <span className={styles.integrityDelta}>{integrityHint}</span>
                ) : null}
              </div>
              <div className={styles.integrityTrack}>
                <motion.div
                  className={styles.integrityFill}
                  initial={{ scaleX: 0 }}
                  animate={{ scaleX: datasetProfile.integrity_percent / 100 }}
                  transition={{ duration: 0.65, ease: easeOut }}
                  style={{ originX: 0 }}
                />
              </div>
            </div>
            <div className={styles.statsGrid}>
              <div>
                <p className={styles.statKicker}>VALORES NULOS</p>
                <p className={styles.statValue}>{null_cells.toLocaleString('es-ES')}</p>
              </div>
              <div>
                <p className={styles.statKicker}>DUPLICADOS</p>
                <p className={styles.statValue}>{duplicate_rows.toLocaleString('es-ES')}</p>
              </div>
            </div>
            {activeFileLabel ? (
              <p className={styles.fileHint}>
                Archivo: <span className={styles.fileName}>{activeFileLabel}</span>
              </p>
            ) : null}
          </motion.div>

          <motion.div
            className={styles.aiCard}
            initial={{ opacity: 0, x: 12 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.42, delay: 0.05, ease: easeOut }}
          >
            <div className={styles.aiRibbon} aria-hidden />
            <div className={styles.aiHead}>
              <MaterialIcon name="auto_awesome" className={styles.aiIcon} />
              <h4 className={styles.aiTitle}>Insight de IA</h4>
            </div>
            <p className={styles.aiBody}>{datasetProfile.ai_hint}</p>
          </motion.div>

          <motion.div
            className={styles.distCard}
            initial={{ opacity: 0, x: 12 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.42, delay: 0.1, ease: easeOut }}
          >
            <h3 className={styles.cardTitle}>Tipos de Datos</h3>
            <ul className={styles.distList}>
              <li className={styles.distItem}>
                <span className={`${styles.distDot} ${styles.distDotBlue}`} />
                <span className={styles.distLabel}>Cadenas (Strings)</span>
                <span className={styles.distCount}>
                  {datasetProfile.type_distribution.strings}
                </span>
                <div className={styles.distBarOuter}>
                  <motion.div
                    className={`${styles.distBarInner} ${styles.distBarBlue}`}
                    initial={{ scaleX: 0 }}
                    animate={{
                      scaleX: datasetProfile.type_distribution.strings / typeTotal,
                    }}
                    transition={{ duration: 0.55, ease: easeOut }}
                    style={{ originX: 0 }}
                  />
                </div>
              </li>
              <li className={styles.distItem}>
                <span className={`${styles.distDot} ${styles.distDotGreen}`} />
                <span className={styles.distLabel}>Numéricos (Float/Int)</span>
                <span className={styles.distCount}>
                  {datasetProfile.type_distribution.numerics}
                </span>
                <div className={styles.distBarOuter}>
                  <motion.div
                    className={`${styles.distBarInner} ${styles.distBarGreen}`}
                    initial={{ scaleX: 0 }}
                    animate={{
                      scaleX: datasetProfile.type_distribution.numerics / typeTotal,
                    }}
                    transition={{ duration: 0.55, delay: 0.05, ease: easeOut }}
                    style={{ originX: 0 }}
                  />
                </div>
              </li>
              <li className={styles.distItem}>
                <span className={`${styles.distDot} ${styles.distDotAmber}`} />
                <span className={styles.distLabel}>Fechas (Datetime)</span>
                <span className={styles.distCount}>
                  {datasetProfile.type_distribution.datetimes}
                </span>
                <div className={styles.distBarOuter}>
                  <motion.div
                    className={`${styles.distBarInner} ${styles.distBarAmber}`}
                    initial={{ scaleX: 0 }}
                    animate={{
                      scaleX: datasetProfile.type_distribution.datetimes / typeTotal,
                    }}
                    transition={{ duration: 0.55, delay: 0.1, ease: easeOut }}
                    style={{ originX: 0 }}
                  />
                </div>
              </li>
            </ul>
          </motion.div>
        </aside>
      </div>
    </WorkspacePage>
  )
}
